apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-api
  labels:
    app: cats-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cats-api
  template:
    metadata:
      labels:
        app: cats-api
    spec:
      containers:
        - name: cats-api
          image: 0539226016/cats-api:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURSE_HOST
              value: 192.168.56.1
            - name: spring.mvc.servlet.path
              value: /cats-api
